drop table if exists product;

create table product (
    identifier  int generated by default as identity (start with 1) primary key,
    name        varchar(255) not null,
    price       int not null
);